In [1]:
import mlflow
logged_model = 'runs:/e9509ed08797416a86028d121b588c19/RandomForestClassifier/with-SMOT'
# Load model as a PyFuncModel.
loaded_model = mlflow.pyfunc.load_model(logged_model)

2024/04/25 05:29:55 WARNING mlflow.utils.requirements_utils: Detected one or more mismatches between the model's dependencies and the current Python environment:
 - cloudpickle (current: 2.2.1, required: cloudpickle==3.0.0)
 - numpy (current: 1.25.2, required: numpy==1.26.4)
 - packaging (current: 23.2, required: packaging==24.0)
 - psutil (current: 5.9.0, required: psutil==5.9.8)
 - pyyaml (current: 5.4.1, required: pyyaml==6.0.1)
 - scipy (current: 1.11.3, required: scipy==1.13.0)
To fix the mismatches, call `mlflow.pyfunc.get_model_dependencies(model_uri)` to fetch the model's environment and install dependencies using the resulting environment file.
2024/04/25 05:29:55 WARNING mlflow.pyfunc: The version of Python that the model was saved in, `Python 3.12.1`, differs from the version of Python that is currently running, `Python 3.9.18`, and may be incompatible


In [2]:
import numpy as np
data = [0.18688110462429236, 0.4065407743462576, 1.1296783711560971, 0.7151698949315407, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0]
data = np.array(data).reshape(1, -1)

In [3]:
# Predict on a Pandas DataFrame.
import pandas as pd
loaded_model.predict(pd.DataFrame(data))

array([0], dtype=int64)

In [15]:
import mlflow
logged_model = 'models:/forest_best_acc/Production'
# Load model as a PyFuncModel.
loaded_model = mlflow.pyfunc.load_model(logged_model)

# Predict on a Pandas DataFrame.
import pandas as pd
loaded_model.predict(pd.DataFrame(data))

2024/04/25 05:39:12 WARNING mlflow.utils.requirements_utils: Detected one or more mismatches between the model's dependencies and the current Python environment:
 - cloudpickle (current: 2.2.1, required: cloudpickle==3.0.0)
 - numpy (current: 1.25.2, required: numpy==1.26.4)
 - packaging (current: 23.2, required: packaging==24.0)
 - psutil (current: 5.9.0, required: psutil==5.9.8)
 - pyyaml (current: 5.4.1, required: pyyaml==6.0.1)
 - scipy (current: 1.11.3, required: scipy==1.13.0)
To fix the mismatches, call `mlflow.pyfunc.get_model_dependencies(model_uri)` to fetch the model's environment and install dependencies using the resulting environment file.
2024/04/25 05:39:12 WARNING mlflow.pyfunc: The version of Python that the model was saved in, `Python 3.12.1`, differs from the version of Python that is currently running, `Python 3.9.18`, and may be incompatible


array([0], dtype=int64)

In [16]:
import mlflow
logged_model = 'models:/forest_best_acc/Staging'
# Load model as a PyFuncModel.
loaded_model = mlflow.pyfunc.load_model(logged_model)

# Predict on a Pandas DataFrame.
import pandas as pd
loaded_model.predict(pd.DataFrame(data))

c:\Users\ammar\AppData\Local\anaconda3\envs\test\lib\site-packages\mlflow\store\artifact\utils\models.py:32: FutureWarning: ``mlflow.tracking.client.MlflowClient.get_latest_versions`` is deprecated since 2.9.0. Model registry stages will be removed in a future major release. To learn more about the deprecation of model registry stages, see our migration guide here: https://mlflow.org/docs/2.12.1/model-registry.html#migrating-from-stages
  latest = client.get_latest_versions(name, None if stage is None else [stage])
2024/04/25 05:40:03 WARNING mlflow.utils.requirements_utils: Detected one or more mismatches between the model's dependencies and the current Python environment:
 - cloudpickle (current: 2.2.1, required: cloudpickle==3.0.0)
 - numpy (current: 1.25.2, required: numpy==1.26.4)
 - packaging (current: 23.2, required: packaging==24.0)
 - psutil (current: 5.9.0, required: psutil==5.9.8)
 - pyyaml (current: 5.4.1, required: pyyaml==6.0.1)
 - scipy (current: 1.11.3, required: scipy=

array([0], dtype=int64)

In [14]:
import mlflow
logged_model = 'models:/forest_best/Staging'
# Load model as a PyFuncModel.
loaded_model = mlflow.pyfunc.load_model(logged_model)

# Predict on a Pandas DataFrame.
import pandas as pd
loaded_model.predict(pd.DataFrame(data))

c:\Users\ammar\AppData\Local\anaconda3\envs\test\lib\site-packages\mlflow\store\artifact\utils\models.py:32: FutureWarning: ``mlflow.tracking.client.MlflowClient.get_latest_versions`` is deprecated since 2.9.0. Model registry stages will be removed in a future major release. To learn more about the deprecation of model registry stages, see our migration guide here: https://mlflow.org/docs/2.12.1/model-registry.html#migrating-from-stages
  latest = client.get_latest_versions(name, None if stage is None else [stage])


MlflowException: No versions of model with name 'forest_best' and stage 'Staging' found

In [13]:
import mlflow
logged_model = 'models:/forest_best/Production'
# Load model as a PyFuncModel.
loaded_model = mlflow.pyfunc.load_model(logged_model)

# Predict on a Pandas DataFrame.
import pandas as pd
loaded_model.predict(pd.DataFrame(data))

c:\Users\ammar\AppData\Local\anaconda3\envs\test\lib\site-packages\mlflow\store\artifact\utils\models.py:32: FutureWarning: ``mlflow.tracking.client.MlflowClient.get_latest_versions`` is deprecated since 2.9.0. Model registry stages will be removed in a future major release. To learn more about the deprecation of model registry stages, see our migration guide here: https://mlflow.org/docs/2.12.1/model-registry.html#migrating-from-stages
  latest = client.get_latest_versions(name, None if stage is None else [stage])
2024/04/25 05:38:55 WARNING mlflow.utils.requirements_utils: Detected one or more mismatches between the model's dependencies and the current Python environment:
 - cloudpickle (current: 2.2.1, required: cloudpickle==3.0.0)
 - numpy (current: 1.25.2, required: numpy==1.26.4)
 - packaging (current: 23.2, required: packaging==24.0)
 - psutil (current: 5.9.0, required: psutil==5.9.8)
 - pyyaml (current: 5.4.1, required: pyyaml==6.0.1)
 - scipy (current: 1.11.3, required: scipy=

array([0], dtype=int64)

In [9]:
import mlflow
logged_model = 'models:/forest_best/Archived'
# Load model as a PyFuncModel.
loaded_model = mlflow.pyfunc.load_model(logged_model)

# Predict on a Pandas DataFrame.
import pandas as pd
loaded_model.predict(pd.DataFrame(data))

c:\Users\ammar\AppData\Local\anaconda3\envs\test\lib\site-packages\mlflow\store\artifact\utils\models.py:32: FutureWarning: ``mlflow.tracking.client.MlflowClient.get_latest_versions`` is deprecated since 2.9.0. Model registry stages will be removed in a future major release. To learn more about the deprecation of model registry stages, see our migration guide here: https://mlflow.org/docs/2.12.1/model-registry.html#migrating-from-stages
  latest = client.get_latest_versions(name, None if stage is None else [stage])
2024/04/25 05:31:42 WARNING mlflow.utils.requirements_utils: Detected one or more mismatches between the model's dependencies and the current Python environment:
 - cloudpickle (current: 2.2.1, required: cloudpickle==3.0.0)
 - numpy (current: 1.25.2, required: numpy==1.26.4)
 - packaging (current: 23.2, required: packaging==24.0)
 - psutil (current: 5.9.0, required: psutil==5.9.8)
 - pyyaml (current: 5.4.1, required: pyyaml==6.0.1)
 - scipy (current: 1.11.3, required: scipy=

array([0], dtype=int64)